# These set of workflows run on every pull request
name: PR Checks
permissions:
  contents: read

on:
  workflow_dispatch:
  pull_request:

jobs:
  linting:
    name: Linting
    uses: ./.github/workflows/lint.yml
  tests:
    name: Tests
    uses: ./.github/workflows/test.yml